import Footer from './components/footer'
import Navbar from './components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <title>Fajrin`s Portfolio Project</title> 
         <link rel="icon" href="/kf.png" sizes="square" />
      </head>     
      <body className={inter.className}>
        <div className='min-h-[100vh] relative'>
          <Navbar />
          <div className='pb-[2.5rem]'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
